### ISSUE TITLE
cuDNN launch failure : input shape ([16,128,7,7])

### ISSUE THREAD

**Issue by evgdobr** [eriklindernoren/Keras-GAN#179]
Hi 

i have next error runnign "python acgan.py"
(Cuda 8, python 2.x) 

```

_________________________________________________________________
conv2d_7 (Conv2D)            (None, 28, 28, 1)         577
_________________________________________________________________
activation_3 (Activation)    (None, 28, 28, 1)         0
=================================================================
Total params: 856,705
Trainable params: 856,065
Non-trainable params: 640
_________________________________________________________________
2019-08-16 15:14:27.747970: I tensorflow/stream_executor/dso_loader.cc:152] successfully opened CUDA library libcublas.so.10.0 locally
2019-08-16 15:14:30.784869: E tensorflow/stream_executor/cuda/cuda_dnn.cc:82] CUDNN_STATUS_EXECUTION_FAILED
in tensorflow/stream_executor/cuda/cuda_dnn.cc(2804): 'cudnnBatchNormalizationForwardTraining( cudnn.handle(), mode, &one, &zero, x_descriptor.handle(), x.opaque(), x_descriptor.handle(), y->opaque(), scale_offset_descriptor.handle(), scale.opaque(), offset.opaque(), 1.0, batch_mean_opaque, batch_var_opaque, epsilon, saved_mean->opaque(), saved_inv_var->opaque())'
Traceback (most recent call last):
  File "acgan.py", line 219, in <module>
    acgan.train(epochs=10000, batch_size=16, sample_interval=200)
  File "acgan.py", line 158, in train
    gen_imgs = self.generator.predict([noise, sampled_labels])
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/training.py", line 1169, in predict
    steps=steps)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/training_arrays.py", line 294, in predict_loop
    batch_outs = f(ins_batch)
  File "/usr/local/lib/python2.7/dist-packages/keras/backend/tensorflow_backend.py", line 2715, in __call__
    return self._call(inputs)
  File "/usr/local/lib/python2.7/dist-packages/keras/backend/tensorflow_backend.py", line 2675, in _call
    fetched = self._callable_fn(*array_vals)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1439, in __call__
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/errors_impl.py", line 528, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InternalError: cuDNN launch failure : input shape ([16,128,7,7])
         [[{{node sequential_2/batch_normalization_3/FusedBatchNorm}}]]
         [[{{node sequential_2/activation_3/Tanh}}]]

```

**Comment by MrRobot2211** [comment]
Per chance are you using tenorflow 2?

**Comment by evgdobr** [comment]
> Per chance are you using tenorflow 2?

no, 
I used TF 1,3
