### ISSUE TITLE
Can't run improved_wgan on Keras2.1.5 with Theano 1.0.1

### ISSUE THREAD

**Issue by CreeperGo** [eriklindernoren/Keras-GAN#24]
Traceback (most recent call last):
  File "improved_wgan.py", line 251, in <module>
    wgan = ImprovedWGAN()
  File "improved_wgan.py", line 84, in __init__
    loss_weights=[1, 1, 10])
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/training.py", line 830, in compile
    sample_weight, mask)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/training.py", line 429, in weighted
    score_array = fn(y_true, y_pred)
  File "improved_wgan.py", line 109, in gradient_penalty_loss
    gradients = K.gradients(y_pred, averaged_samples)[0]
  File "/usr/local/lib/python2.7/dist-packages/keras/backend/theano_backend.py", line 1240, in gradients
    return T.grad(loss, variables)
  File "/usr/local/lib/python2.7/dist-packages/theano/gradient.py", line 487, in grad
    raise TypeError("cost must be a scalar.")
TypeError: cost must be a scalar.

**Comment by eriklindernoren** [comment]
I have not tested the implementation with a Theano backend yet. I have used Tensorflow for all implementations so far. Can you get it to run with a TF backend instead?
