### ISSUE TITLE
srgan doesn't run?

### ISSUE THREAD

**Issue by ktbyte** [eriklindernoren/Keras-GAN#27]
I receive this error when running srgan.py:

`Traceback (most recent call last):
  File "srgan.py", line 263, in <module>
    gan.train(epochs=30000, batch_size=1, sample_interval=50)
  File "srgan.py", line 192, in train
    imgs_hr, imgs_lr = self.data_loader.load_data(batch_size)
  File "/home/ubuntu/Keras-GAN/srgan/data_loader.py", line 16, in load_data
    batch_images = np.random.choice(path, size=batch_size)
  File "mtrand.pyx", line 1126, in mtrand.RandomState.choice
ValueError: a must be non-empty
`

Additionally, the example for srgan.py references 'steps at the top of' the file. However, I cannot find such steps:

`$ cd srgan/
<follow steps at the top of srgan.py>
$ python3 srgan.py`

**Comment by eriklindernoren** [comment]
Oh, must have forgot to push those changes. The error stems from the fact that the dataset is missing. The instructions that you need to follow in order to get the script to run are added in 5c18953.
