### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by serdaraslan** [eriklindernoren/Keras-GAN#37]
Wgan gives error when I run the code

Traceback (most recent call last):
  File "wgan.py", line 190, in <module>
    wgan = WGAN()
  File "wgan.py", line 33, in __init__
    self.critic = self.build_critic()
  File "wgan.py", line 109, in build_critic
    img = Input(shape=img_shape)
NameError: name 'img_shape' is not defined

Is the code finished?

**Comment by eriklindernoren** [comment]
Hi. Thanks. This is fixed in 78333e9
