### ISSUE TITLE
 output_shape=lambda p: p[0]) TypeError: 'module' object is not callable

### ISSUE THREAD

**Issue by wustczx** [eriklindernoren/Keras-GAN#83]
Excuse me,I configured as described, and when I run python aae. py, an error occurred as follows:
Using TensorFlow backend.
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
dense_1 (Dense)              (None, 512)               5632      
_________________________________________________________________
leaky_re_lu_1 (LeakyReLU)    (None, 512)               0         
_________________________________________________________________
dense_2 (Dense)              (None, 256)               131328    
_________________________________________________________________
leaky_re_lu_2 (LeakyReLU)    (None, 256)               0         
_________________________________________________________________
dense_3 (Dense)              (None, 1)                 257       
=================================================================
Total params: 137,217
Trainable params: 137,217
Non-trainable params: 0
_________________________________________________________________
Traceback (most recent call last):
  File "aae.py", line 189, in <module>
    aae = AdversarialAutoencoder()
  File "aae.py", line 36, in __init__
    self.encoder = self.build_encoder()
  File "aae.py", line 72, in build_encoder
    output_shape=lambda p: p[0])
TypeError: 'module' object is not callable

what can I do? Please help me,thank you

**Comment by wustczx** [comment]
questions:https://stackoverflow.com/questions/51075666/how-to-implement-merge-from-keras-layers

so,Merge cannot be used with a sequential model, Which version of keras do you use?

**Comment by niunno** [comment]
import Lambda layer
`from keras.layers import Lambda`
then, replace 
`latent_repr = merge([mu, log_var],
                mode=lambda p: p[0] + K.random_normal(K.shape(p[0])) * K.exp(p[1] / 2),
                output_shape=lambda p: p[0])`
with 
`latent_repr = Lambda(lambda p: p[0] + K.random_normal(K.shape(p[0])) * K.exp(p[1] / 2), lambda p: p[0])([mu, log_var])`
