### ISSUE TITLE
Unable to handle images of arbitrary shape

### ISSUE THREAD

**Issue by luileito** [eriklindernoren/Keras-GAN#95]
It seems the input images must have a 1:1 aspect ratio, right? I tried to train the network with rectangular images (`width > height`) but I got the following error:
```
Traceback (most recent call last):
  File "pix2pix.py", line 214, in <module>
    gan = Pix2Pix()
  File "pix2pix.py", line 55, in __init__
    self.generator = self.build_generator()
  File "pix2pix.py", line 109, in build_generator
    u1 = deconv2d(d7, d6, self.gf*8)
  File "pix2pix.py", line 93, in deconv2d
    u = Concatenate()([u, skip_input])
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py", line 594, in __call__
    self.build(input_shapes)
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/merge.py", line 354, in build
    'Got inputs shapes: %s' % (input_shape))
ValueError: A `Concatenate` layer requires inputs with matching shapes except for the concat axis. Got inputs shapes: [(None, 2, 2, 512), (None, 2, 1, 512)]
```
Is there a way to handle images with rectangular size?

**Comment by eps696** [comment]
one workaround for non-degree-of-two sizes is to save shapes while convoluting and resize back to those shapes while deconvoluting. works pretty well for the sizes of the same order (like 640x480 instead of 512x512).

here is my generator with such approach :: 

```
    def build_generator(self): # U-Net Generator

        def conv2d(layer_input, filters, f_size=4):
            d = Conv2D(filters, kernel_size=f_size, strides=2, padding='same')(layer_input)
            d = LeakyReLU(alpha=0.2)(d)
            d = InstanceNormalization()(d)
            return d

        def l_resize(input, size):
            if a.phase == 'train':
                out = UpSampling2D(size=2)(input)
            else:
                try:
                    out = Lambda(lambda input: K.tf.image.resize_images(input, size, method=tf.image.ResizeMethod.NEAREST_NEIGHBOR))(input)
                except:
                    # if you have older version of tensorflow
                    out = Lambda(lambda input: K.tf.image.resize_images(input, size[0], size[1], method=tf.image.ResizeMethod.NEAREST_NEIGHBOR))(input)
            return tf.cast(out, dtype=tf.float32) # tf.to_float(out)

        def deconv2d(layer_input, size, skip_input, filters, f_size=4, dropout_rate=0):
            u = l_resize(layer_input, size) # !!!
            u = Conv2D(filters, kernel_size=f_size, strides=1, padding='same', activation='relu')(u)
            if dropout_rate:
                u = Dropout(dropout_rate)(u)
            u = InstanceNormalization()(u)
            u = Concatenate()([u, skip_input])
            return u

        # Image input
        d0 = Input(shape=self.img_shape)
        
        res_list = []
        shape_cur = d0.get_shape().as_list()
        res_list.append([self.img_shape[0], self.img_shape[1]])
        # Downsampling
        d1 = conv2d(d0, self.gf)
        shape_cur = d1.get_shape().as_list()
        res_list.append([shape_cur[1], shape_cur[2]])
        d2 = conv2d(d1, self.gf*2)
        shape_cur = d2.get_shape().as_list()
        res_list.append([shape_cur[1], shape_cur[2]])
        d3 = conv2d(d2, self.gf*4)
        shape_cur = d3.get_shape().as_list()
        res_list.append([shape_cur[1], shape_cur[2]])
        d4 = conv2d(d3, self.gf*8)
        shape_cur = d4.get_shape().as_list()
        res_list.append([shape_cur[1], shape_cur[2]])
        d5 = conv2d(d4, self.gf*8) # added !!!
        shape_cur = d5.get_shape().as_list()
        res_list.append([shape_cur[1], shape_cur[2]])
        d6 = conv2d(d5, self.gf*8) # added !!!
#        print("res_list", res_list) # [[512,512,128], [256,256,128], [128,128,256], [64,64,512], [32,32,1024], [16,16,1024]]
        # Upsampling
        u1 = deconv2d(d6, res_list[5], d5, self.gf*8) # added !!!
        u2 = deconv2d(u1, res_list[4], d4, self.gf*8) # added !!!
        u3 = deconv2d(u2, res_list[3], d3, self.gf*4)
        u4 = deconv2d(u3, res_list[2], d2, self.gf*2)
        u5 = deconv2d(u4, res_list[1], d1, self.gf)
        # final
        u6 = l_resize(u5, res_list[0]) # !!!
        output_img = Conv2D(self.channels, kernel_size=4, strides=1, padding='same', activation='tanh')(u6)
#        print(output_img.get_shape())

        return Model(d0, output_img)

```

**Comment by mrgloom** [comment]
One way is to pad image with zeros to power of 2, for example for VGA 640×480 -> 1024x512 and then estimate number of downsample layers, but maybe it will hurt GAN quality.
